### ISSUE TITLE
Support latest Kubernetes versions

### ISSUE THREAD

**Issue by vitality411** [vmware/cloud-provider-for-cloud-director#123]
### Is your feature request related to a problem? Please describe.

It is not possible to use CCM with latest Kubernetes versions e.g. K8s from 1.22 till 1.24

### Describe the solution you'd like

Add support for latest Kubernetes versions

**Comment by arunmk** [comment]
@vitality411 can you mention what problem you faced while using CPI with 1.22+?

**Comment by vitality411** [comment]
@arunmk I have not tried it with 1.22+ 
If there are no known issues with 1.22+ then it should suffice to updated the README.md with the latest K8s versions.

**Comment by ltimothy7** [comment]
CPI 1.2.0 and 1.3.0 are advertised to support k8s 1.22 based on our qualification. CPI should work with other k8s versions, but these require further qualification.
