### ISSUE TITLE
nil pointer exception when ovdcnetwork belongs to a vdcgroup

### ISSUE THREAD

**Issue by erkanerol** [vmware/cloud-provider-for-cloud-director#236]
### Describe the bug

We hit a nil pointer exception because of this change https://github.com/vmware/cluster-api-provider-cloud-director/commit/3c10715a9c5459c490bed43575a353fa20c90c86#diff-59b60be5f954bd671a4e14145d5d90fa00ac1585211788e31632b9df9b84a8f7R122.

`ovdcNetwork.OrgVdc` is nil in our case. 

### Reproduction steps

1. Deploy the cloud provider by using an OVDCNetwork that belongs to a VDC group.

### Expected behavior

The provider shouldn't crash.

### Additional context

Slack thread: https://kubernetes.slack.com/archives/C04JFT7GDGR/p1677700001396329

See this line https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/model_vdc_network.go#L36
```
The organization vDC the network belongs to. This should be unset if the network is owned by a vDC Group.
```

**Comment by ltimothy7** [comment]
Thank you @erkanerol. We are looking into this fixing this.
