### ISSUE TITLE
Image in manifests /cloud-director-ccm.yaml does not longer exists 

### ISSUE THREAD

**Issue by ricardo-larosa** [vmware/cloud-provider-for-cloud-director#238]
### Describe the bug

Hi this image `cloud-provider-for-cloud-director:main-branch.8946fef` which is in `manifests/cloud-director-ccm.yaml` was removed.

```sh
docker pull harbor-repo.vmware.com/vcloud/cloud-provider-for-cloud-director:main-branch.8946fef
Error response from daemon: unknown: artifact vcloud/cloud-provider-for-cloud-director:main-branch.8946fef not found
```

Making this manifest to fail.

### Reproduction steps

1. `docker pull harbor-repo.vmware.com/vcloud/cloud-provider-for-cloud-director:main-branch.8946fef`

### Expected behavior

Pull complete should ocurr

**Comment by ltimothy7** [comment]
Hi Ricardo, main-branch images are part of our dev processes and are not reliable being present. We recommend using images from official releases, which can be found by going to the appropriate tag. Please let us know if we can help or if there is a reason you would like to use a development image.
