### ISSUE TITLE
Creation of vCD NSX-T DNATs should include application

### ISSUE THREAD

**Issue by jleavers** [vmware/cloud-provider-for-cloud-director#43]
### Describe the bug

If we create a LoadBalancer service in Kubernetes with port 80 and 443 - like the service created with https://projectcontour.io/quickstart/contour.yaml - the following happens:

2x ALB virtual services are created
2x ALB server pools are created
2x DNATs are created using the same public IP, that NAT through to the different IPs & ports used by the ALB virtual services, e.g.

1. x.x.x.x -> 192.168.8.2:80
2. x.x.x.x -> 192.168.8.3:443

We can then add the required firewall rule, e.g. allow all HTTP/HTTPS traffic to the ALB network 192.168.8.0/24 for example. 

If the vCD Edge Gateway is backed by an NSX-T Tier-1 gateway, this will not work. Only one of the DNATs will work, e.g. HTTP will work but HTTPS will not. If we disable the HTTP DNAT, the HTTPS DNAT will start working. 

If we connect directly to the 192.168.8.x IP of the ALB, both work.

The fix is to add applications to the NSX-T DNAT rules, e.g. HTTP and HTTPS as per the screenshot. 

![DNATs](https://user-images.githubusercontent.com/11852680/150560506-0032076a-fde7-425e-9e53-7eb4d33d00d1.jpg)

Ideally these would be added during the creation of the DNAT rule. 

This was seen with vCD 10.3.2 and NSX-T 3.1.3.5.0.

### Reproduction steps

```bash
1. Create k8s Loadbalancer service using vCD/NSX-T ALB/NSX-T Tier-1 Edge. DNATs will be created using a single public IP but different internal IPs/ports.
2. Test traffic direct to both ALB virtual services on their private IPs - OK
3. Test traffic to public DNAT IP - only one works. Disable HTTP DNAT - HTTPS will work.
```

### Expected behavior

Traffic to DNATs using a single public IP that is directed to different internal IPs/ports should work.

It works if applications are added to the DNATs via vCD.

Ideally these should be added during the automated creation of the rules.

**Comment by arunmk** [comment]
@jleavers we have fixed this in the main branch and the upcoming 1.1.0 release (Jan/27) should resolve this.

**Comment by jleavers** [comment]
Thanks! I can see that the application is now added to each DNAT.

![appPorts](https://user-images.githubusercontent.com/11852680/151994539-00d10e4c-6f6e-40cd-ad9f-7e7016201f50.PNG)
