### ISSUE TITLE
User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in 1.1.0

### ISSUE THREAD

**Issue by jleavers** [vmware/cloud-provider-for-cloud-director#48]
### Describe the bug

I was running 1.0.2 on k8s v1.21.2+vmware.1, and edited the deployment vmware-cloud-director-ccm to change the image to projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director:1.1.0.latest.

The new vmware-cloud-director-ccm pod then logged continual messages like this, and no new NATs/ALBs were created in vCD: 

```
E0201 14:52:00.261818       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0201 14:52:03.107259       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0201 14:52:06.108764       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0201 14:52:10.287091       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
E0201 14:52:14.167106       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

I edited the clusterrole (kubectl -n kube-system edit clusterrole system:cloud-controller-manager) and added the following to the end:

```
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
```

After this the lease was acquired and NATs/ALBs were created again. 

### Reproduction steps

```bash
1. Upgrade to 1.1.0
2. Tail the logs for the new ccm pod
3. See permissions error relating to leases
4. New NAT/ALB config is not added
```

### Expected behavior

Service account should have correct permissions
NATs/ALBs should be created following upgrade, as before

**Comment by an0nz** [comment]
I ran into this same issue when upgrading to 1.1.0 for testing. Once adding in the missing rules this error immediately went away for me.

The system:cloud-controller-manager ClusterRole has been updated with additional rules so you need to also update that as per
https://github.com/vmware/cloud-provider-for-cloud-director/blob/87a513209519d60545b386e1a6b41880837fe31e/manifests/cloud-director-ccm.yaml#L7-L113

**Comment by arunmk** [comment]
@an0nz @jleavers this is hit since we upgraded some libraries for 1.1.0. The corresponding manifest (https://github.com/vmware/cloud-provider-for-cloud-director/blob/1.1.0/manifests/cloud-director-ccm.yaml) has the required rights.


Do you concur and think we can close this issue?

**Comment by jleavers** [comment]
Hi @arunmk - when upgrading, should I do something in addition to simply changing the image version in the deployment to ensure these additions/changes are captured? i.e. how should we 'know' that the cloud-director-ccm.yaml also needs to change.

**Comment by arunmk** [comment]
@jleavers the manifest file is a set of properties which describe the environment where the container is to be run. So ideally, the way to upgrade would be to delete the old deployment and apply the manifest in 1.1.0 directly. The manifest already points to the right image.

**Comment by arunmk** [comment]
@jleavers as in, the following commands can be run:
```
kubectl delete deployment -n kube-system vmware-cloud-director-ccm
kubectl apply -f https://raw.githubusercontent.com/vmware/cloud-provider-for-cloud-director/1.1.0/manifests/cloud-director-ccm.yaml
```

**Comment by jleavers** [comment]
Okay great - thanks!
